# Commit to `production-android` branch → build with EAS

name: production-android → build Android app

on:
  push:
    branches:
      - production-android

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Publish app to Expo/EAS
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto

      - name: 🛠️ Build app
        run: EAS_BUILD_AUTOCOMMIT=1 eas build --non-interactive --platform android

      - name: 🚚 Submit app to TestFlight
        run: eas submit --latest --platform android
